### ISSUE TITLE
Fix .References

### ISSUE THREAD

**Issue by hrudham** [marlanperumal/poker_simulator#2]
A lot of the references are done with a preceding point:

e.g.: `import .Thing from Thing`

This allows the poker-app to work with this module, but means you encounter an error when trying to execute this module via the console:

```
Traceback (most recent call last):
  File ".\Simulation.py", line 1, in <module>
    from .Deck import Deck
SystemError: Parent module '' not loaded, cannot perform relative import
```

In order for the latter to work, you have to change all files to be `import Thing from Thing`.

We need to find out why this happens and fix it so that both work.

**Comment by marlanperumal** [comment]
Changed all imports to do absolute references from the full package. This means that the package must be in the PYTHONPATH or used in a virtual environment where it has been added to the path
