### ISSUE TITLE
Rename repository to poker_simulator

### ISSUE THREAD

**Issue by hrudham** [marlanperumal/poker_simulator#3]
We need to rename this repository to `poker_simulator` (with an underscore). The reasoning here is that, by default, executing `git pull [url]` will create a directory with called `poker-simulator` (with a dash). This is not a valid name in python however, so breaks imports of this module, and thus may be confusing for developers working with this for the first time.

The alternative is to edit the read-me to explain this, and use the `git pull [url] poker_simulator` command instead.

**Comment by marlanperumal** [comment]
renamed
